# Homepage Content
title: Hack for Savannah - A National Day of Civic Hacking Event
eventName: Hack for Savannah 2017
eventDate: Sept. 22-24, 2017 @ Bull Street Labs
opensavannahURL: https://opensavannah.org
Eventbrite: https://www.eventbrite.com/countdown-widget?eid=37262881281
conference_date: Sept. 22-24 @ 2222 Bull St.
checkin: Check-in, kickoff reception and panel begins at 6:00 p.m. Friday.
overviewImg: https://cvlassets.s3.amazonaws.com/0817-open_savannah_sav_maps-13.jpg
openSavannahGH: https://github.com/opensavannah
funTime: https://photos.app.goo.gl/D2hkIXsEdCM0twwO2
creativePeople: https://www.meetup.com/OpenSavannah/members/
civicHackathon: https://opensavannah.org/what-is-a-civic-hackathon
codeForAmerica: http://codeforamerica.org
savbook: https://savbook.io
openbudgetsav: http://openbudgetsav.org
email: yall@opensavannah.org
twitterList: https://twitter.com/open_savannah/lists/open-savannah-leadership
twitterWidget: //platform.twitter.com/widgets.js
downloadSchedule: https://s3.amazonaws.com/cvlassets/hackforsavannah.pdf
dayOneDate: Sept. 22, 2017
dayTwoDate: Sept. 23, 2017
dayThreeDate: Sept. 24, 2017


spekers-tickets-info:
  - title: 7 expert judges
    icon: fa-microphone
  - title: 100 ticket limit
    icon: fa-ticket
  - title: $6000 in cash prizes
    icon: fa-money
  - title: 1.5 days of hacking
    icon: fa-calendar-check-o

sponsors-row-1:
  - img: https://cvlassets.s3.amazonaws.com/sedalogo.png
    url: http://seda.org
  - img: https://s3.amazonaws.com/lightning-carlvlewis/atdc-logo.png
    url: http://atdc.org
  - img: https://s3.amazonaws.com/cvlassets/Screen%20Shot%202017-09-01%20at%206.24.35%20PM.png
    url: http://codebasesav.com
  - img: http://oak.works/img/logos/oakworks.svg
    url: http://oak.works


sponsors-row-2:
  - img: https://s3.amazonaws.com/cvlassets/creative-coast_1.jpg
    url: http://creativecoast.organization
  - img: https://s3.amazonaws.com/cvlassets/lopl.jpg
    url: http://liveoakpl.org
  - img: https://s3.amazonaws.com/cvlassets/tFT3yPC7_400x400.jpg
    url: /
  - img: https://s3.amazonaws.com/cvlassets/city-of-savannah-1%202.jpg
    url: http://savannahga.gov

sponsors-row-3:
  - img: https://s3.amazonaws.com/cvlassets/header_logo.png
    url: /

# Build settings
markdown: kramdown
permalink: pretty
